name: My First Github Action
on: [push]
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps: # steps of arrays to be run
      - run: echo "hello world!!!!!!"
      - run: echo "this is step number 2"
