name: My First Github Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps: # steps of arrays to be run
      - uses: actions/checkout@v2  #clone current running dirctory
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build the project
        run: yarn build
      - name: Setup finish
        run: echo "hurray!"
