name: My First Github Action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps: # steps of arrays to be run
      - uses: actions/checkout@v2  #clone current running dirctory
      - run: tree # can alo run ls
